language: node_js
node_js:
  - "8"
deploy:
  - provider: script
    on:
      branch: master
    script:
    - npx semantic-release
    skip_cleanup: true
after_success:
  branches:
    only:
      - master
  - npm run build
